service: aws-test-proj

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  region: "eu-central-1"
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: 
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Get*"
            - "dynamodb:Scan*"
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-testTable-${sls:stage}
  environment:
    DYNAMODB_TEST_TABLE: ${self:service}-testTable-${sls:stage}


functions:
  hello:
    handler: handler.hello


resources:
  Resources:
    TestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-testTable-${sls:stage}
        StreamSpecification:
          StreamViewType: NEW_IMAGE